"""Shared drum vocabulary for pro8 chart generation."""

from __future__ import annotations

KICK_LABEL = "kick"
SNARE_LABEL = "snare"
HIHAT_LABEL = "hihat"
TOM_YELLOW_LABEL = "tom_yellow"
RIDE_LABEL = "ride"
TOM_BLUE_LABEL = "tom_blue"
CRASH_LABEL = "crash"
TOM_GREEN_LABEL = "tom_green"

PRO8_LABELS = [
    KICK_LABEL,
    SNARE_LABEL,
    HIHAT_LABEL,
    TOM_YELLOW_LABEL,
    RIDE_LABEL,
    TOM_BLUE_LABEL,
    CRASH_LABEL,
    TOM_GREEN_LABEL,
]

KICK = 0
SNARE = 1
YELLOW_PAD = 2
BLUE_PAD = 3
GREEN_PAD = 4

CYMBAL_YELLOW = 66
CYMBAL_BLUE = 67
CYMBAL_GREEN = 68

PAD_NOTES = frozenset({KICK, SNARE, YELLOW_PAD, BLUE_PAD, GREEN_PAD})
HAND_PAD_NOTES = frozenset({SNARE, YELLOW_PAD, BLUE_PAD, GREEN_PAD})
CYMBAL_MODIFIERS = frozenset({CYMBAL_YELLOW, CYMBAL_BLUE, CYMBAL_GREEN})

CYMBAL_BY_PAD = {
    YELLOW_PAD: CYMBAL_YELLOW,
    BLUE_PAD: CYMBAL_BLUE,
    GREEN_PAD: CYMBAL_GREEN,
}
PAD_BY_CYMBAL = {cymbal: pad for pad, cymbal in CYMBAL_BY_PAD.items()}

INSTRUMENT_TO_CHART_NOTES: dict[str, tuple[int, int | None]] = {
    KICK_LABEL: (KICK, None),
    SNARE_LABEL: (SNARE, None),
    HIHAT_LABEL: (YELLOW_PAD, CYMBAL_YELLOW),
    TOM_YELLOW_LABEL: (YELLOW_PAD, None),
    RIDE_LABEL: (BLUE_PAD, CYMBAL_BLUE),
    TOM_BLUE_LABEL: (BLUE_PAD, None),
    CRASH_LABEL: (GREEN_PAD, CYMBAL_GREEN),
    TOM_GREEN_LABEL: (GREEN_PAD, None),
}

MAX_HAND_LANES = 2
HAND_LANE_PRIORITY = {
    SNARE: 0,
    GREEN_PAD: 1,
    BLUE_PAD: 2,
    YELLOW_PAD: 3,
}
HAND_INSTRUMENT_PRIORITY = (
    SNARE_LABEL,
    CRASH_LABEL,
    RIDE_LABEL,
    HIHAT_LABEL,
    TOM_YELLOW_LABEL,
    TOM_BLUE_LABEL,
    TOM_GREEN_LABEL,
)
